# Generated by Django 4.2.17 on 2025-12-27 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thiết bị')),
                ('device_type', models.CharField(choices=[('relay', 'Relay (Bật/Tắt)'), ('sensor', 'Cảm biến')], default='relay', max_length=20, verbose_name='Loại thiết bị')),
                ('value', models.CharField(default='0', help_text='Relay: 0=OFF, 1=ON | Sensor: giá trị đo được', max_length=50, verbose_name='Giá trị')),
                ('unit', models.CharField(blank=True, help_text='VD: °C, %, ppm...', max_length=20, null=True, verbose_name='Đơn vị')),
                ('is_online', models.BooleanField(default=False, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thiết bị',
                'verbose_name_plural': 'Thiết bị',
                'ordering': ['-updated_at'],
            },
        ),
    ]
