# Generated by Django 4.2.17 on 2025-12-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thiết bị', 'verbose_name_plural': 'Thiết bị'},
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Giá trị')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Log cảm biến',
                'verbose_name_plural': 'Logs cảm biến',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='devices_sen_device__ca7d10_idx')],
            },
        ),
    ]
