# Generated by Django 4.2.17 on 2025-12-27 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_alter_device_options_sensorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_code',
            field=models.CharField(blank=True, help_text='VD: v1, v2, v3...', max_length=10, null=True, verbose_name='Mã thiết bị'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'device_code')},
        ),
    ]
