# Generated by Django 4.2.17 on 2025-12-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_device_code_alter_device_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
    ]
