# Generated by Django 4.2.17 on 2025-12-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_device_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Thời gian'),
        ),
    ]
