# Generated by Django 4.2.17 on 2025-12-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_sensorlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='enable_logging',
            field=models.BooleanField(default=False, verbose_name='Ghi log đồ thị'),
        ),
    ]
