# Generated by Django 4.2.17 on 2025-12-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key dùng để kết nối thiết bị qua MQTT', max_length=64, null=True, unique=True, verbose_name='API Key'),
        ),
    ]
