# Generated by Django 4.2.17 on 2025-12-27 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=50, unique=True, verbose_name='Mã người dùng')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_users', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sở hữu')),
            ],
            options={
                'verbose_name': 'Người dùng Face ID',
                'verbose_name_plural': 'Người dùng Face ID',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'user_code')},
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_event', models.CharField(blank=True, choices=[('checkin', 'Check-in'), ('checkout', 'Check-out'), ('check', 'Check')], max_length=20, null=True, verbose_name='Sự kiện cuối')),
                ('last_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian cuối')),
                ('face_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_status', to='face_recognition.faceuser', verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Trạng thái nhận diện',
                'verbose_name_plural': 'Trạng thái nhận diện',
            },
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500, verbose_name='Đường dẫn ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('face_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to='face_recognition.faceuser', verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Ảnh khuôn mặt',
                'verbose_name_plural': 'Ảnh khuôn mặt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('checkin', 'Check-in'), ('checkout', 'Check-out'), ('check', 'Check')], default='check', max_length=20, verbose_name='Loại sự kiện')),
                ('confidence', models.FloatField(default=0, verbose_name='Độ tin cậy')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('face_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='face_recognition.faceuser', verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử điểm danh',
                'verbose_name_plural': 'Lịch sử điểm danh',
                'ordering': ['-timestamp'],
            },
        ),
    ]
